### ISSUE TITLE
关于React Native中【根据变量的值是否为空来控制组件的显示与否】的问题小结 | 个人博客

### ISSUE THREAD

**Issue by yinshangwei** [yinshangwei/yinshangwei.github.io#2]
https://yinshangwei.github.io/2017/11/24/about-raw-text-error/

**Comment by yinshangwei** [comment]
国内的评论系统都不让用了啊，现在暂时选择第5种。
1.多说
2.网易云跟帖
3.畅言
4.Disqus
5.Gitment

**Comment by liyuanhust** [comment]
👍
